---
packages:
  - vim
  - parted
  - prometheus-node-exporter

ceph_packages:
  - ceph
  - ceph-common
  - ceph-fuse
  - ceph-mds
  - ceph-volume
  - jq
  - gdisk
  - nvme-cli
  - radosgw
  - s3cmd

remove_repos:
  - /etc/apt/sources.list.d/pve-enterprise.sources

radosgw_port: 7480
velero_backup_bucket: velero-backup
docker_registry_bucket: docker-registry
